modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="panmod"
version="1.2.0"
displayName="panmod"
credits="."
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Payload9"

[[dependencies.panmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




